from . import advancement
from . import attribute
from . import ban
from . import ban_ip
from . import clear
from . import clone
from . import damage
from . import data
from . import datapack
from . import debug
from . import defaultgamemode
from . import deop
from . import difficulty
from . import effect
from . import enchant
from . import execute
from . import experience
from . import fill
from . import function
from . import gamemode
from . import gamerule
from . import give
from . import help
from . import item
from . import jfr
from . import kick
from . import kill
from . import locate
from . import op
from . import pardon
from . import pardon_ip
from . import perf
from . import publish
from . import recipe
from . import reload
from . import return_cmd
from . import ride
from . import rotate
from . import save_all
from . import save_off
from . import save_on
from . import schedule
from . import scoreboard
from . import seed
from . import setblock
from . import setworldspawn
from . import spawnpoint
from . import spectate
from . import spreadplayers
from . import stop
from . import stopwatch
from . import summon
from . import tag
from . import tick
from . import time
from . import tp
from . import visual_cmds
from . import waypoint
from . import weather
from . import whitelist
from . import worldborder
from . import xp
from ..command_tree.dispatcher import dispatcher

__all__ = ["dispatcher"]
